spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: constructor
      authentication-database: none
  messages:
    encoding: UTF-8
    fallback-to-system-locale: false
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.istyazhkina.constructor.changelogs